export const Icons = {
    "new_create_index" : "plus-square-o",
    "my_game_index" : "smile-o",
    "label_index" : "tag-o",
    "all_game_index" : "book",
    "admin_index" : "laptop",
    "new_create_game" : 'plus-circle-o',
    "new_create_company" : 'plus',
    "my_game_edit" : 'edit',
    "my_game_create" : 'inbox',
    "label_create" : 'tags-o',
    "label_game_info" : 'camera-o',
    "label_game_dim" : 'bulb',
    "label_company_info" : 'appstore-o',
    "all_game_check_list" : "eye-o",
    "all_game_list" : "hdd",
    "all_game_company_list" : "appstore-o",
    "admin_user_index" : "solution",
    "admin_role_index" : "team",
    "admin_perm_index" : "safety",
    "admin_send_msg" : "notification"
}
